-- KORVATTU 2026-08-05, EI KOSKAAN AJETTU TUOTANNOSSA — jätetty paikoilleen
-- no-opina ettei numero 095 katoa migraatiohistoriasta hämmentävästi.
--
-- Alkuperäinen versio toi koodauskurssin + matikkaradan KOKONAAN 95
-- taitosolmuna. Katri täsmensi 2026-08-05 taitosolmujen määritelmän:
-- taitosolmu (silta) syntyy VAIN kun sama käsite esiintyy kahdessa tai
-- useammassa AKTIIVISESSA kurssissa yhtä aikaa — yksittäisellä kurssilla ei
-- koskaan ole omaa taitosolmuverkkoa. Alkuperäinen tuonti mallinsi väärin
-- koko kurssisisällön taitosolmuina, kun se kuuluu opinto_kurssit/
-- opinto_aiheet-radalle (ks. sql/100, joka tuo saman sisällön oikein).
--
-- Täysi kuvaus uudesta mallista: muistiinpanot.md "Siltasolmut" -osio.
--
-- Ei sisällä komentoja — turvallinen ajaa (ei tee mitään).
