-- KORVATTU 2026-08-05, EI KOSKAAN AJETTU TUOTANNOSSA — jätetty paikoilleen
-- no-opina ettei numero 096 katoa migraatiohistoriasta hämmentävästi.
--
-- Alkuperäiset testirivit (OSA AH) kuvasivat sql/095:n vanhaa, korvattua
-- taitosolmumallia (yksittäiset esimerkkisolmut kuten "muuttujat" jotka
-- eivät enää synny taitosolmuina, ks. sql/095:n yläkommentti). Uudet
-- testirivit samasta ominaisuudesta, oikeaa mallia vastaten: sql/101.
--
-- Ei sisällä komentoja — turvallinen ajaa (ei tee mitään).
