-- Kolmiportainen kadenssi, Taso 2 (VAIHE2_JA_LISAYKSET_CODELLE.md,
-- 18.8.2026) — "ainoa taso joka yhä kysyy". Sama malli kuin
-- silta_ehdotukset_odottavat (sql/094): moottori EHDOTTAA, rivi jää
-- 'kasitelty=false' -tilaan kunnes Katri hyväksyy/hylkää dismissible-
-- kortilla. Hyväksyntä vaihtaa opinto_kurssit.hoitotaso, hylkäys vain
-- merkitsee käsitellyksi (ei vaihda mitään) — kummassakin tapauksessa uusi
-- ehdotus samalle kurssille voi syntyä vasta seuraavalla diagnoosikierroksella.
--
-- Aja tämä Supabasen SQL Editorissa.

begin;

create table if not exists opinto_hoitotaso_ehdotukset (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id),
  kurssi_id bigint not null references opinto_kurssit(id) on delete cascade,
  ehdotettu_hoitotaso text not null check (ehdotettu_hoitotaso in ('kevyt', 'vain_deadlinet')),
  perustelu text not null,
  luotu_at timestamptz not null default now(),
  kasitelty boolean not null default false
);

alter table opinto_hoitotaso_ehdotukset enable row level security;

create policy "opinto_hoitotaso_ehdotukset_all" on opinto_hoitotaso_ehdotukset
  for all using (owner_id = (select auth.uid())) with check (owner_id = (select auth.uid()));

commit;
