-- Harjoitustehtävägeneraattori (2026-08-29, Katrin build brief "Practice
-- Problem Generator"). Fysiikan kurssin oppikirja (College Physics for AP®
-- Courses 2e, ~1800 sivua/255MB PDF) EI koskaan käsitellä PDF:nä — kirja on
-- vapaasti luettavissa openstax.org:ssa, joten haetaan vain ne osiot jotka
-- opettaja on jo merkinnyt aiheen otsikkoon (ks. api/_lib/openstax-osiot.js).
--
-- openstax_sections: opettajan kuratoimat luku.osio-viitteet ("4.5" jne.).
-- openstax_cache: haetun osiotekstin välimuisti, täyttyy ensimmäisellä
--   käytöllä (avaimena osio- tai luku-tunniste), ei koskaan haeta uudelleen.
-- materiaali_teksti: varakonteksti niille aiheille joilla EI ole yhtään
--   OpenStax-osiota (esim. "1 - Fundamental Physics Skills", "5 – ICT and
--   sustainability" — eivät vastaa yhtäkään tämän oppikirjan lukua). Sisältö
--   on jo olemassa olevaa kalvomateriaalia (laituri.content), kopioitu
--   suoraan tänne — EI koko kirjaa, sama kokoluokka kuin yksi OpenStax-osio.
--
-- harjoitustehtavat: generoidut tehtävät. ratkaisu-saraketta ei koskaan
-- palauteta ensimmäisessä generointivastauksessa (ks. api/luo-harjoitustehtava.js) —
-- vain api/nayta-ratkaisu.js palauttaa sen erikseen pyydettäessä.
-- skenaario on lyhyt kuvaus jota käytetään toistumisen estoon (Katrin
-- nimenomainen pyyntö: "i don't want to see exactly same question with same
-- numbers twice").
--
-- Idempotentti (add column/create table if not exists). Ajettu jo suoraan
-- MCP:n kautta 29.8.2026 - tämä tiedosto on historiakirjaus (ks. sql/138:n
-- vastaava malli).

begin;

alter table opinto_aiheet add column if not exists openstax_sections text[] not null default '{}';
alter table opinto_aiheet add column if not exists openstax_cache jsonb not null default '{}'::jsonb;
alter table opinto_aiheet add column if not exists materiaali_teksti text;

create table if not exists harjoitustehtavat (
  id bigint generated by default as identity primary key,
  aihe_id bigint not null references opinto_aiheet(id) on delete cascade,
  kurssi_id bigint not null references opinto_kurssit(id) on delete cascade,
  pacer_vaihe text not null default 'encoding' check (pacer_vaihe in ('priming','encoding','retrieval','connection')),
  kysymys text not null,
  ratkaisu text not null,
  vihje text,
  skenaario text,
  luotu_at timestamptz not null default now(),
  owner_id uuid not null
);

create index if not exists harjoitustehtavat_aihe_idx on harjoitustehtavat (aihe_id, luotu_at desc);

alter table harjoitustehtavat enable row level security;

drop policy if exists harjoitustehtavat_all on harjoitustehtavat;
create policy harjoitustehtavat_all on harjoitustehtavat
  for all
  using (owner_id = auth.uid())
  with check (owner_id = auth.uid());

commit;
