-- Yleiskäyttöinen kurssitason "yhdistämis"-Miro-alueiden taulu (2026-08-26,
-- Katrin pyyntö: "would be nice to have some sort of Exam A kind of function
-- when for example precalculus is done to mix and match topics creatively
-- & find different conections.."). sql/149:n miro_exam_a_url/miro_exam_b_url
-- riittää kursseille joilla on tasan kaksi oikeaa tenttiä, mutta Math
-- Roadmapissa on neljä luonnollista klusteria (Precalculus/Calculus/Applied
-- Mathematics/Statistics) eikä yhtään oikeaa tenttiä — siksi tämä on erillinen
-- N-rivinen taulu eikä lisää kiinteitä sarakkeita opinto_kurssit-tauluun.
-- Exam A/B -mekanismi jätetään koskemattomaksi niille kursseille (Engineering
-- Physics, Introduction to Mathematical Sciences) joilla se jo toimii.
--
-- UI: kurssinäkymässä yksi nappi per rivi (🔗/➕🔗 + nimi), sama avaa-tai-
-- kysy-promptilla-logiikka kuin Exam A/B -napeissa
-- (ks. script.js:n piirraOpintoKurssinYhteysalueet).
--
-- Ajettu jo suoraan MCP:n kautta 26.8.2026 (mukaan lukien neljän rivin
-- alkusiemennys Math Roadmapille, kurssi id=2) - tämä tiedosto on
-- historiakirjaus (ks. sql/138:n vastaava malli).

begin;

create table if not exists opinto_yhteysalueet (
  id bigint generated by default as identity primary key,
  kurssi_id bigint not null references opinto_kurssit(id) on delete cascade,
  nimi text not null,
  miro_url text,
  sort_order bigint not null default 0,
  created_at timestamptz not null default now()
);

alter table opinto_yhteysalueet enable row level security;

create policy opinto_yhteysalueet_all on opinto_yhteysalueet
  for all
  using (exists (select 1 from opinto_kurssit k where k.id = kurssi_id and k.owner_id = auth.uid()))
  with check (exists (select 1 from opinto_kurssit k where k.id = kurssi_id and k.owner_id = auth.uid()));

insert into opinto_yhteysalueet (kurssi_id, nimi, sort_order) values
  (2, 'Precalculus – yhteydet', 100),
  (2, 'Calculus – yhteydet', 200),
  (2, 'Applied Mathematics for ICT – yhteydet', 300),
  (2, 'Statistics and Probability – yhteydet', 400);

commit;
