-- Taukolista (2026-08-31, Katrin muistelema Sung/PACER-keskustelu "Hytti V5",
-- kysymykset 146-158, ei koskaan tallennettu mihinkään repon dokumenttiin —
-- teoreettinen perusta on kuitenkin kirjattuna sung-metodi.md §21 (Lepo ja
-- palautuminen): rentoutuminen on matalaa aktiivisuutta KUORMITTUNEELLE
-- järjestelmälle, ei sama asia kuin vaivaton puhelimen selaus ("matalan
-- vaivan kiihtymys"), neljä palautumisen ulottuvuutta, "15-20 min itse
-- valittua riittää".
--
-- Ensimmäinen vaihe kolmesta/neljästä osasta (ks. muistin
-- project_taukojarjestelma, jos/kun kirjoitetaan) — Katrin oma valinta:
-- "Taukolista first" ennen push-pohjaista 30-45min-rytmimuistutusta,
-- kalenteriin etukäteen suunniteltuja isoja palautumisankkureita, ja
-- 2h-paikallaanolo-/punaisen-päivän-muistutuksia.
--
-- Katrin päättämä malli: "Satama pulls from without AI — random draw or
-- fixed order, either is fine" — valittu satunnaisarvonta joka painottaa
-- pisimpään ehdottamatta ollutta (viimeksi_ehdotettu_at). "Picking a
-- suggestion creates the entry — a tick that a break was taken is enough,
-- no minutes" — tauko_kirjaukset on pelkkä täppäys, ei kestoa.

begin;

create table if not exists taukolista (
  id bigint generated by default as identity primary key,
  owner_id uuid not null,
  teksti text not null,
  viimeksi_ehdotettu_at timestamptz,
  created_at timestamptz not null default now()
);

alter table taukolista enable row level security;

create policy "taukolista_all" on taukolista for all
  using (owner_id = (select auth.uid()))
  with check (owner_id = (select auth.uid()));

create table if not exists tauko_kirjaukset (
  id bigint generated by default as identity primary key,
  owner_id uuid not null,
  taukolista_id bigint references taukolista(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table tauko_kirjaukset enable row level security;

create policy "tauko_kirjaukset_all" on tauko_kirjaukset for all
  using (owner_id = (select auth.uid()))
  with check (owner_id = (select auth.uid()));

create index if not exists tauko_kirjaukset_owner_id_idx on tauko_kirjaukset (owner_id);

-- Alkusiemennys (Katrin oma toive: 5 min lihaskunto/venyttely mukaan) —
-- sung-metodi.md §21:n yhteensopivat poiminnat: ulkoilu, liikunta, paikan
-- vaihtaminen, ei ruutuja, siivous ilman taustaääntä, 5-10 min torkut.
insert into taukolista (owner_id, teksti) values
  ('d646881e-0ab8-4351-aae1-3e92678c8432', '5 min venyttely tai kevyt lihaskuntoliike'),
  ('d646881e-0ab8-4351-aae1-3e92678c8432', '10 kyykkyä tai punnerrusta'),
  ('d646881e-0ab8-4351-aae1-3e92678c8432', '15 min kävely ulkona'),
  ('d646881e-0ab8-4351-aae1-3e92678c8432', 'Vaihda huonetta muutamaksi minuutiksi'),
  ('d646881e-0ab8-4351-aae1-3e92678c8432', 'Katso ulos ikkunasta ilman puhelinta'),
  ('d646881e-0ab8-4351-aae1-3e92678c8432', 'Venyttele niska ja hartiat'),
  ('d646881e-0ab8-4351-aae1-3e92678c8432', 'Juo lasillinen vettä rauhassa, ilman ruutua'),
  ('d646881e-0ab8-4351-aae1-3e92678c8432', 'Siivoa jokin pieni asia ilman taustaääntä'),
  ('d646881e-0ab8-4351-aae1-3e92678c8432', '5-10 min torkut'),
  ('d646881e-0ab8-4351-aae1-3e92678c8432', 'Käsillä tekemistä ilman ruutua (esim. pyykin ripustus)');

commit;
